### Importing library

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# import plotly.express as px
import plotly.graph_objects as go

In [2]:
data = pd.DataFrame()

df = pd.read_csv("./dataset/nifty500_1d.csv")
df.head()

,Datetime,Ticker,Company,Open,High,Low,Close,Volume
0,2019-09-19 09:15:00+05:30,360ONE,360 ONE WAM Ltd.,302.500,317.625,302.500,317.6250,7109860
1,2019-09-20 09:15:00+05:30,360ONE,360 ONE WAM Ltd.,332.250,333.500,332.250,333.5000,2760648
2,2019-09-23 09:15:00+05:30,360ONE,360 ONE WAM Ltd.,350.175,350.175,350.175,350.1750,34096
3,2019-09-24 09:15:00+05:30,360ONE,360 ONE WAM Ltd.,367.675,367.675,367.675,367.6750,2496652
4,2019-09-25 09:15:00+05:30,360ONE,360 ONE WAM Ltd.,386.050,386.050,349.300,351.2375,530580

In [3]:
df.dtypes

Datetime        str
Ticker          str
Company         str
Open        float64
High        float64
Low         float64
Close       float64
Volume        int64
dtype: object

In [4]:
# converting the str to date time format

df['Datetime'] = pd.to_datetime(df['Datetime'])

In [5]:
df.head()

,Datetime,Ticker,Company,Open,High,Low,Close,Volume
0,2019-09-19 09:15:00+05:30,360ONE,360 ONE WAM Ltd.,302.500,317.625,302.500,317.6250,7109860
1,2019-09-20 09:15:00+05:30,360ONE,360 ONE WAM Ltd.,332.250,333.500,332.250,333.5000,2760648
2,2019-09-23 09:15:00+05:30,360ONE,360 ONE WAM Ltd.,350.175,350.175,350.175,350.1750,34096
3,2019-09-24 09:15:00+05:30,360ONE,360 ONE WAM Ltd.,367.675,367.675,367.675,367.6750,2496652
4,2019-09-25 09:15:00+05:30,360ONE,360 ONE WAM Ltd.,386.050,386.050,349.300,351.2375,530580

### Missing data

In [6]:
# df.info()
# no missing data
df["Ticker"].unique()

<StringArray>
[    '360ONE',    '3MINDIA',  'AADHARHFC',   'AARTIIND',      'AAVAS',
        'ABB', 'ABBOTINDIA',  'ABCAPITAL',      'ABFRL',      'ABLBL',
 ...
 'WELSPUNLIV',  'WHIRLPOOL',      'WIPRO', 'WOCKPHARMA',    'YESBANK',
       'ZEEL', 'ZENSARTECH',     'ZENTEC',  'ZFCVINDIA',  'ZYDUSLIFE']
Length: 501, dtype: str

### Find the date ranges and length i.e 15 years of each 500 stocks

In [7]:
new_df = df.copy().groupby("Ticker")['Datetime'].agg(['min','max']).reset_index()

new_df.rename(columns={'min': 'start', 'max': 'end'}, inplace=True)

new_df['duration'] = (new_df['end'] - new_df['start']).dt.days / 365.25

new_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 501 entries, 0 to 500
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Ticker    501 non-null    str
 1   start     501 non-null    datetime64[us, UTC+05:30]
 2   end       501 non-null    datetime64[us, UTC+05:30]
 3   duration  501 non-null    float64
dtypes: datetime64[us, UTC+05:30](2), float64(1), str(1)
memory usage: 15.8 KB

In [8]:
new_df.sample(500)

         Ticker                     start                       end   duration
476    UNITDSPR 2006-11-02 09:15:00+05:30 2026-02-23 09:15:00+05:30  19.310062
348    NLCINDIA 2006-11-02 09:15:00+05:30 2026-02-23 09:15:00+05:30  19.310062
326  MOTILALOFS 2007-09-11 09:15:00+05:30 2026-02-23 09:15:00+05:30  18.453114
240    INOXWIND 2015-04-09 09:15:00+05:30 2026-02-23 09:15:00+05:30  10.877481
80       BIKAJI 2022-11-16 09:15:00+05:30 2026-02-23 09:15:00+05:30   3.271732
..          ...                       ...                       ...        ...
394     RBLBANK 2016-08-31 09:15:00+05:30 2026-02-23 09:15:00+05:30   9.481177
397   REDINGTON 2007-02-15 09:15:00+05:30 2026-02-23 09:15:00+05:30  19.022587
474  ULTRACEMCO 2005-12-02 09:15:00+05:30 2026-02-23 09:15:00+05:30  20.227242
426       SOBHA 2006-12-20 09:15:00+05:30 2026-02-23 09:15:00+05:30  19.178645
410    SAPPHIRE 2021-11-18 09:15:00+05:30 2026-02-23 09:15:00+05:30   4.265572

[500 rows x 4 columns]

### Visualising the OHCLV data as candles

In [9]:
target_ticker = '360ONE'
ticker_df = df[df['Ticker'] == target_ticker].copy()
ticker_df = ticker_df.sort_values('Datetime')

In [10]:
fig = go.Figure(data=[go.Candlestick(
    x=ticker_df['Datetime'],
    open=ticker_df['Open'],
    high=ticker_df['High'],
    low=ticker_df['Low'],
    close=ticker_df['Close'],
    
    # Optional: Customize the colors for bullish/bearish candles
    increasing_line_color='green', 
    decreasing_line_color='red'
)])

# 4. Update the layout to make it look professional
fig.update_layout(
    title=f'{target_ticker} Historical Price Action',
    yaxis_title='Stock Price',
    xaxis_title='Date',
    
    # Plotly adds a large range slider at the bottom by default. 
    # Setting this to False gives you a cleaner, traditional chart view.
    xaxis_rangeslider_visible=False,
    
    # Use a clean white background
    template='plotly_white'
)

# 5. Display the interactive chart
fig.show()